const scenes = [
  ['晨霧山谷','山巒 · 日出'],['蔚藍海岸','海灣 · 暖陽'],['高山之鏡','湖泊 · 晨光'],['赤色峽谷','沙漠 · 夕照'],['極光之夜','峽灣 · 星空'],
  ['櫻色湖畔','春日 · 花影'],['金色稻田','田野 · 秋收'],['雨林秘境','瀑布 · 綠意'],['燈塔之島','海島 · 黃昏'],['雪夜小鎮','村落 · 冬季'],
  ['薰衣草原','花田 · 夏日'],['雲端茶園','山坡 · 清晨'],['珊瑚海灣','海洋 · 晴空'],['火山之晨','火山 · 朝霞'],['森林溪谷','溪流 · 午後'],
  ['月下沙丘','沙漠 · 月光'],['秋楓古橋','河谷 · 秋色'],['冰川藍湖','冰原 · 晴日'],['梯田晚霞','田園 · 日落'],['星空草原','草原 · 夜色']
].map(([title,subtitle],index)=>({title,subtitle,index,url:`assets/landscape-${String(index+1).padStart(2,'0')}.jpg`}));

const $ = id => document.getElementById(id);
const gallery = $('galleryGrid');
const board = $('board');
let current = 0, size = 4, pieces = [], moves = 0, seconds = 0, hints = 2, selected = -1, timer = null, playing = false, soundOn = true, gesture = null, ignoreClick = false;
const saved = (()=>{try{return JSON.parse(localStorage.getItem('shijing-records')||'{}')}catch{return {}}})();

function saveRecords(){try{localStorage.setItem('shijing-records',JSON.stringify(saved))}catch{}}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function playTone(freq=480){if(!soundOn)return;try{const context=new (window.AudioContext||window.webkitAudioContext)(),o=context.createOscillator(),g=context.createGain();o.type='sine';o.frequency.setValueAtTime(freq,context.currentTime);o.frequency.exponentialRampToValueAtTime(freq*1.25,context.currentTime+.08);g.gain.setValueAtTime(.035,context.currentTime);g.gain.exponentialRampToValueAtTime(.001,context.currentTime+.13);o.connect(g).connect(context.destination);o.start();o.stop(context.currentTime+.14);o.onended=()=>context.close()}catch{}}
function renderGallery(){gallery.innerHTML='';scenes.forEach(scene=>{const card=document.createElement('button');card.className='gallery-card';card.type='button';card.setAttribute('aria-label',`開始拼圖：${scene.title}`);const completed=Object.keys(saved).some(key=>key.startsWith(`${scene.index}-`));card.innerHTML=`<div class="card-image" style="background-image:url('${scene.url}')"><span class="card-number">${String(scene.index+1).padStart(2,'0')} / 20</span>${completed?'<span class="card-completed">✓ 已完成</span>':''}</div><div class="card-content"><div><strong>${scene.title}</strong><small>${scene.subtitle}</small></div><span class="card-arrow">↗</span></div>`;card.addEventListener('click',()=>openGame(scene.index));gallery.append(card)})}
function shuffle(){pieces=Array.from({length:size*size},(_,i)=>i);for(let i=pieces.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pieces[i],pieces[j]]=[pieces[j],pieces[i]]}if(pieces.filter((p,i)=>p===i).length>pieces.length/3){return shuffle()}if(pieces.every((p,i)=>p===i))return shuffle();moves=0;seconds=0;hints=2;selected=-1;playing=true;clearInterval(timer);timer=setInterval(()=>{if(playing){seconds++;$('timeDisplay').textContent=formatTime(seconds)}},1000);renderBoard();updateStats();updateBest()}
function openGame(index){current=index;$('gameTitle').textContent=scenes[index].title;$('previewImage').style.backgroundImage=`url('${scenes[index].url}')`;$('gameOverlay').hidden=false;$('winOverlay').hidden=true;document.body.style.overflow='hidden';setDifficulty(size);$('closeButton').focus()}
function closeGame(){playing=false;clearInterval(timer);$('gameOverlay').hidden=true;$('winOverlay').hidden=true;document.body.style.overflow='';renderGallery()}
function setDifficulty(n){size=n;document.querySelectorAll('#difficulty button').forEach(b=>{const active=Number(b.dataset.size)===size;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active?'true':'false')});shuffle()}
function renderBoard(){board.style.gridTemplateColumns=`repeat(${size},1fr)`;board.innerHTML='';const url=scenes[current].url;pieces.forEach((piece,index)=>{const tile=document.createElement('button');tile.className='tile'+(piece===index?' correct':'')+(selected===index?' selected':'');tile.type='button';tile.dataset.index=index;tile.setAttribute('aria-label',`第 ${Math.floor(index/size)+1} 列，第 ${index%size+1} 行的方塊`);tile.style.backgroundImage=`url('${url}')`;tile.style.backgroundSize=`${size*100}% ${size*100}%`;tile.style.backgroundPosition=`${(piece%size)/(size-1)*100}% ${Math.floor(piece/size)/(size-1)*100}%`;board.append(tile)})}
function adjacent(a,b){return Math.abs(Math.floor(a/size)-Math.floor(b/size))+Math.abs(a%size-b%size)===1}
function swap(a,b){if(!playing||!adjacent(a,b))return;[pieces[a],pieces[b]]=[pieces[b],pieces[a]];moves++;selected=-1;playTone(400+Math.random()*100);renderBoard();updateStats();if(pieces.every((p,i)=>p===i))win()}
function updateStats(){$('timeDisplay').textContent=formatTime(seconds);$('movesDisplay').textContent=moves;$('progressDisplay').textContent=`${pieces.filter((p,i)=>p===i).length}/${pieces.length}`;$('hintCount').textContent=hints;$('hintButton').disabled=hints<=0}
function updateBest(){const record=saved[`${current}-${size}`];$('bestLine').textContent=record?`個人最佳：${formatTime(record.time)} · ${record.moves} 步`:'這幅風景還沒有完成紀錄。'}
function win(){playing=false;clearInterval(timer);const key=`${current}-${size}`,previous=saved[key];if(!previous||seconds<previous.time||(seconds===previous.time&&moves<previous.moves)){saved[key]={time:seconds,moves};saveRecords()}const target=size*size*2;const stars=moves<=target?'★★★':moves<=target*2?'★★☆':'★☆☆';$('winText').textContent=`「${scenes[current].title}」已完整歸位。下一段旅程也在等你。`;$('winTime').textContent=formatTime(seconds);$('winMoves').textContent=moves;$('winStars').textContent=stars;$('winOverlay').hidden=false;playTone(660);setTimeout(()=>$('nextButton').focus(),50)}
function showHint(){if(!playing||hints<=0)return;const misplaced=pieces.map((p,i)=>p===i?-1:i).filter(i=>i>=0);if(!misplaced.length)return;const from=misplaced[Math.floor(Math.random()*misplaced.length)],to=pieces[from];hints--;updateStats();const cells=board.children;cells[from]?.classList.add('hinted');cells[to]?.classList.add('hinted');setTimeout(()=>{cells[from]?.classList.remove('hinted');cells[to]?.classList.remove('hinted')},2500);playTone(760)}
board.addEventListener('pointerdown',e=>{const tile=e.target.closest('.tile');if(!tile)return;gesture={index:Number(tile.dataset.index),x:e.clientX,y:e.clientY};tile.setPointerCapture?.(e.pointerId)});
board.addEventListener('pointerup',e=>{if(!gesture)return;const {index,x,y}=gesture;gesture=null;const dx=e.clientX-x,dy=e.clientY-y;if(Math.max(Math.abs(dx),Math.abs(dy))<24)return;ignoreClick=true;setTimeout(()=>ignoreClick=false,30);const target=Math.abs(dx)>Math.abs(dy)?index+(dx>0?1:-1):index+(dy>0?size:-size);swap(index,target)});
board.addEventListener('pointercancel',()=>gesture=null);
board.addEventListener('click',e=>{if(ignoreClick)return;const tile=e.target.closest('.tile');if(!tile)return;const index=Number(tile.dataset.index);if(selected>=0&&adjacent(selected,index)){swap(selected,index)}else{selected=selected===index?-1:index;renderBoard();if(selected>=0)board.children[selected]?.focus()}});
board.addEventListener('keydown',e=>{const tile=e.target.closest('.tile');if(!tile)return;const index=Number(tile.dataset.index);const delta={ArrowUp:-size,ArrowDown:size,ArrowLeft:-1,ArrowRight:1}[e.key];if(delta===undefined)return;e.preventDefault();const target=index+delta;if(target>=0&&target<pieces.length&&adjacent(index,target)){swap(index,target);board.children[target]?.focus()}});
document.querySelectorAll('#difficulty button').forEach(button=>button.addEventListener('click',()=>setDifficulty(Number(button.dataset.size))));
$('shuffleButton').addEventListener('click',shuffle);$('hintButton').addEventListener('click',showHint);$('closeButton').addEventListener('click',closeGame);$('backButton').addEventListener('click',closeGame);$('galleryButton').addEventListener('click',closeGame);$('nextButton').addEventListener('click',()=>openGame((current+1)%scenes.length));$('soundButton').addEventListener('click',()=>{soundOn=!soundOn;$('soundButton').setAttribute('aria-pressed',String(soundOn));$('soundButton').querySelector('span').textContent=soundOn?'音效開':'音效關'});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('gameOverlay').hidden)closeGame()});
$('heroArt').style.backgroundImage=`url('${scenes[0].url}')`;renderGallery();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
