const scenes = [
  ['晨霧山谷','山巒 · 日出'],['蔚藍海岸','海灣 · 暖陽'],['高山之鏡','湖泊 · 晨光'],['赤色峽谷','沙漠 · 夕照'],['極光之夜','峽灣 · 星空'],
  ['櫻色湖畔','春日 · 花影'],['金色稻田','田野 · 秋收'],['雨林秘境','瀑布 · 綠意'],['燈塔之島','海島 · 黃昏'],['雪夜小鎮','村落 · 冬季'],
  ['薰衣草原','花田 · 夏日'],['雲端茶園','山坡 · 清晨'],['珊瑚海灣','海洋 · 晴空'],['火山之晨','火山 · 朝霞'],['森林溪谷','溪流 · 午後'],
  ['月下沙丘','沙漠 · 月光'],['秋楓古橋','河谷 · 秋色'],['冰川藍湖','冰原 · 晴日'],['梯田晚霞','田園 · 日落'],['星空草原','草原 · 夜色'],
  ['風鈴牧場','草坡 · 微風'],['琥珀森林','林間 · 金秋'],['白沙潟湖','海岸 · 潮汐'],['雲霧竹林','山徑 · 清晨'],['紅葉瀑布','溪谷 · 深秋'],
  ['月桂古城','石城 · 黃昏'],['紫藤庭園','花園 · 春雨'],['琥珀海岬','峭壁 · 落日'],['雪杉山徑','森林 · 初雪'],['蒸汽小站','山城 · 薄霧'],
  ['玻璃湖泊','湖畔 · 晨霜'],['金砂海灘','海島 · 暮色'],['鳶尾花谷','花谷 · 晴日'],['雲海索道','高山 · 雲端'],['松林溪橋','溪流 · 夏蔭'],
  ['藍冰洞窟','冰川 · 藍光'],['古樹草原','原野 · 黃昏'],['翡翠稻埕','田園 · 晨曦'],['珊瑚日落','礁岸 · 晚霞'],['白樺湖畔','湖泊 · 秋陽'],
  ['星河峽谷','峽谷 · 夜空'],['橙色燈塔','海角 · 夕陽'],['霧中石階','山寺 · 雲霧'],['薰風花海','花田 · 暖風'],['銀河雪原','雪原 · 星空'],
  ['晨曦葡萄園','丘陵 · 日出'],['藍山瀑谷','山谷 · 午後'],['火紅楓林','森林 · 晚秋'],['靜謐港灣','海港 · 夜色'],['白雲峰頂','高峰 · 晴空']
].map(([title,subtitle],index)=>({title,subtitle,index,url:`assets/landscape-${String(index+1).padStart(2,'0')}.jpg`}));
const TOTAL_LEVELS = scenes.length;

const $ = id => document.getElementById(id);
const gallery = $('galleryGrid');
const board = $('board');
let current = 0, size = 4, pieces = [], moves = 0, seconds = 0, hints = 2, selected = -1, timer = null, playing = false, soundOn = true, gesture = null, ghost = null, ignoreClick = false, gameHistoryActive = false, backNoticeTimer = null;
let deferredInstallPrompt = null;
const saved = (()=>{try{return JSON.parse(localStorage.getItem('shijing-records')||'{}')}catch{return {}}})();
const activeSessionKey = 'shijing-active-session';
const baseUrl = `${location.pathname}${location.search}`;

function saveRecords(){try{localStorage.setItem('shijing-records',JSON.stringify(saved))}catch{}}
function saveActiveSession(){if(!playing)return;try{localStorage.setItem(activeSessionKey,JSON.stringify({current,size,pieces,moves,seconds,hints}))}catch{}}
function clearActiveSession(){try{localStorage.removeItem(activeSessionKey)}catch{}}
function readActiveSession(){try{const session=JSON.parse(localStorage.getItem(activeSessionKey)||'null');if(!session||!Number.isInteger(session.current)||session.current<0||session.current>=TOTAL_LEVELS||![4,5,6].includes(session.size)||!Array.isArray(session.pieces)||session.pieces.length!==session.size*session.size||session.pieces.some(piece=>!Number.isInteger(piece)||piece<0||piece>=session.pieces.length)||new Set(session.pieces).size!==session.pieces.length)return null;return session}catch{return null}}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function playTone(freq=480){if(!soundOn)return;try{const context=new (window.AudioContext||window.webkitAudioContext)(),o=context.createOscillator(),g=context.createGain();o.type='sine';o.frequency.setValueAtTime(freq,context.currentTime);o.frequency.exponentialRampToValueAtTime(freq*1.25,context.currentTime+.08);g.gain.setValueAtTime(.035,context.currentTime);g.gain.exponentialRampToValueAtTime(.001,context.currentTime+.13);o.connect(g).connect(context.destination);o.start();o.stop(context.currentTime+.14);o.onended=()=>context.close()}catch{}}
function isCompleted(index){return Object.keys(saved).some(key=>key.startsWith(`${index}-`))}
function nextLevel(){const index=scenes.findIndex(scene=>!isCompleted(scene.index));return index<0?0:index}
function renderGallery(){const next=nextLevel(),done=scenes.filter(scene=>isCompleted(scene.index)).length,session=readActiveSession();gallery.innerHTML='';$('levelProgress').textContent=`已完成 ${done} / ${TOTAL_LEVELS} 關`;$('progressFill').style.width=`${done/TOTAL_LEVELS*100}%`;$('levelCount').textContent=`共 ${TOTAL_LEVELS} 關`;$('continueButton').innerHTML=session?`繼續第 ${session.current+1} 關 <span>→</span>`:done===TOTAL_LEVELS?`重玩第 1 關 <span>→</span>`:`開始第 ${next+1} 關 <span>→</span>`;scenes.forEach(scene=>{const card=document.createElement('button');card.className='level-card';card.type='button';const completed=isCompleted(scene.index),unlocked=completed||scene.index<=next;card.classList.toggle('completed',completed);card.classList.toggle('current',scene.index===next&&!completed);card.disabled=!unlocked;card.setAttribute('aria-label',`第 ${scene.index+1} 關：${scene.title}${unlocked?'':'，尚未解鎖'}`);card.innerHTML=`<span class="level-number">LEVEL ${String(scene.index+1).padStart(2,'0')}</span><span class="level-arrow">${completed?'✓':unlocked?'→':'·'}</span><span class="level-title">${unlocked?scene.title:'尚未解鎖'}</span><span class="level-status">${completed?'已完成':unlocked?'點擊開始':'完成前一關後開啟'}</span>`;if(unlocked)card.addEventListener('click',()=>openGame(scene.index));gallery.append(card)})}
function startTimer(){clearInterval(timer);timer=setInterval(()=>{if(playing){seconds++;$('timeDisplay').textContent=formatTime(seconds);saveActiveSession()}},1000)}
function shuffle(){pieces=Array.from({length:size*size},(_,i)=>i);for(let i=pieces.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pieces[i],pieces[j]]=[pieces[j],pieces[i]]}if(pieces.filter((p,i)=>p===i).length>pieces.length/3){return shuffle()}if(pieces.every((p,i)=>p===i))return shuffle();moves=0;seconds=0;hints=2;selected=-1;playing=true;startTimer();renderBoard();updateStats();updateBest();saveActiveSession()}
function enterGameHistory(){if(gameHistoryActive)return;try{history.pushState({shijingGame:true},'',`${baseUrl}#game`);gameHistoryActive=true}catch{}}
function leaveGameHistory(){if(!gameHistoryActive)return;try{history.replaceState(null,'',baseUrl)}catch{}gameHistoryActive=false}
function showBackNotice(){const notice=$('backNotice');notice.hidden=false;clearTimeout(backNoticeTimer);backNoticeTimer=setTimeout(()=>{notice.hidden=true},2400)}
function openGame(index){const wasOpen=!$('gameOverlay').hidden;if(!wasOpen){clearActiveSession();enterGameHistory()}current=index;$('gameTitle').textContent=scenes[index].title;$('previewImage').style.backgroundImage=`url('${scenes[index].url}')`;$('gameOverlay').hidden=false;$('winOverlay').hidden=true;document.body.style.overflow='hidden';setDifficulty(size);$('closeButton').focus()}
function resumeGame(session){current=session.current;size=session.size;pieces=[...session.pieces];moves=session.moves;seconds=session.seconds;hints=session.hints;selected=-1;playing=true;$('gameTitle').textContent=scenes[current].title;$('previewImage').style.backgroundImage=`url('${scenes[current].url}')`;$('gameOverlay').hidden=false;$('winOverlay').hidden=true;document.body.style.overflow='hidden';document.querySelectorAll('#difficulty button').forEach(button=>{const active=Number(button.dataset.size)===size;button.classList.toggle('active',active);button.setAttribute('aria-pressed',active?'true':'false')});renderBoard();updateStats();updateBest();startTimer();enterGameHistory();$('closeButton').focus()}
function closeGame(){saveActiveSession();playing=false;clearInterval(timer);$('gameOverlay').hidden=true;$('winOverlay').hidden=true;document.body.style.overflow='';leaveGameHistory();renderGallery()}
function setDifficulty(n){size=n;document.querySelectorAll('#difficulty button').forEach(b=>{const active=Number(b.dataset.size)===size;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active?'true':'false')});shuffle()}
function renderBoard(){board.style.gridTemplateColumns=`repeat(${size},1fr)`;board.innerHTML='';const url=scenes[current].url;pieces.forEach((piece,index)=>{const tile=document.createElement('button');tile.className='tile'+(piece===index?' correct':'')+(selected===index?' selected':'');tile.type='button';tile.dataset.index=index;tile.setAttribute('aria-label',`第 ${Math.floor(index/size)+1} 列，第 ${index%size+1} 行的方塊`);tile.style.backgroundImage=`url('${url}')`;tile.style.backgroundSize=`${size*100}% ${size*100}%`;tile.style.backgroundPosition=`${(piece%size)/(size-1)*100}% ${Math.floor(piece/size)/(size-1)*100}%`;board.append(tile)})}
function adjacent(a,b){return Math.abs(Math.floor(a/size)-Math.floor(b/size))+Math.abs(a%size-b%size)===1}
function swap(a,b){if(!playing||a===b||a<0||b<0||a>=pieces.length||b>=pieces.length)return;[pieces[a],pieces[b]]=[pieces[b],pieces[a]];moves++;selected=-1;playTone(400+Math.random()*100);renderBoard();updateStats();if(pieces.every((p,i)=>p===i))win();else saveActiveSession()}
function updateStats(){$('timeDisplay').textContent=formatTime(seconds);$('movesDisplay').textContent=moves;$('progressDisplay').textContent=`${pieces.filter((p,i)=>p===i).length}/${pieces.length}`;$('hintCount').textContent=hints;$('hintButton').disabled=hints<=0}
function updateBest(){const record=saved[`${current}-${size}`];$('bestLine').textContent=record?`個人最佳：${formatTime(record.time)} · ${record.moves} 步`:'這幅風景還沒有完成紀錄。'}
function win(){playing=false;clearInterval(timer);clearActiveSession();const key=`${current}-${size}`,previous=saved[key];if(!previous||seconds<previous.time||(seconds===previous.time&&moves<previous.moves)){saved[key]={time:seconds,moves};saveRecords()}const target=size*size*2,scene=scenes[current],stars=moves<=target?'★★★':moves<=target*2?'★★☆':'★☆☆';$('winImage').style.backgroundImage=`url('${scene.url}')`;$('winImage').setAttribute('aria-label',`完成的拼圖：${scene.title}`);$('winText').textContent=`「${scene.title}」已完整歸位。${current<scenes.length-1?'下一關已解鎖，你可以準備好再繼續。':`恭喜完成全部 ${TOTAL_LEVELS} 關！`}`;$('winTime').textContent=formatTime(seconds);$('winMoves').textContent=moves;$('winStars').textContent=stars;$('nextButton').textContent=current<scenes.length-1?'下一關 →':'重玩第一關 →';$('winOverlay').hidden=false;playTone(660);setTimeout(()=>$('nextButton').focus(),50)}
function showHint(){if(!playing||hints<=0)return;const misplaced=pieces.map((p,i)=>p===i?-1:i).filter(i=>i>=0);if(!misplaced.length)return;const from=misplaced[Math.floor(Math.random()*misplaced.length)],to=pieces[from];hints--;updateStats();saveActiveSession();const cells=board.children;cells[from]?.classList.add('hinted');cells[to]?.classList.add('hinted');setTimeout(()=>{cells[from]?.classList.remove('hinted');cells[to]?.classList.remove('hinted')},2500);playTone(760)}
function tileAtPoint(x,y){const rect=board.getBoundingClientRect();if(x<rect.left||x>=rect.right||y<rect.top||y>=rect.bottom)return -1;const col=Math.min(size-1,Math.floor((x-rect.left)/rect.width*size)),row=Math.min(size-1,Math.floor((y-rect.top)/rect.height*size));return row*size+col}
function clearDragMarks(){board.querySelectorAll('.dragging,.drop-target').forEach(tile=>tile.classList.remove('dragging','drop-target'))}
function clearGhost(){ghost?.remove();ghost=null}
board.addEventListener('pointerdown',e=>{const tile=e.target.closest('.tile');if(!tile||!playing)return;gesture={index:Number(tile.dataset.index),x:e.clientX,y:e.clientY,pointerId:e.pointerId};tile.setPointerCapture?.(e.pointerId)});
board.addEventListener('pointermove',e=>{if(!gesture||e.pointerId!==gesture.pointerId)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)<12)return;if(!ghost){const tile=board.children[gesture.index],rect=tile.getBoundingClientRect();ghost=tile.cloneNode();ghost.className='drag-ghost';ghost.style.width=`${rect.width}px`;ghost.style.height=`${rect.height}px`;document.body.append(ghost)}ghost.style.left=`${e.clientX}px`;ghost.style.top=`${e.clientY}px`;clearDragMarks();board.children[gesture.index]?.classList.add('dragging');const target=tileAtPoint(e.clientX,e.clientY);if(target>=0&&target!==gesture.index)board.children[target]?.classList.add('drop-target')});
board.addEventListener('pointerup',e=>{if(!gesture||e.pointerId!==gesture.pointerId)return;const {index,x,y}=gesture;gesture=null;clearDragMarks();clearGhost();if(Math.hypot(e.clientX-x,e.clientY-y)<18)return;ignoreClick=true;setTimeout(()=>ignoreClick=false,50);swap(index,tileAtPoint(e.clientX,e.clientY))});
board.addEventListener('pointercancel',()=>{gesture=null;clearDragMarks();clearGhost()});
board.addEventListener('click',e=>{if(ignoreClick)return;const tile=e.target.closest('.tile');if(!tile)return;const index=Number(tile.dataset.index);if(selected>=0&&selected!==index){swap(selected,index)}else{selected=selected===index?-1:index;renderBoard();if(selected>=0)board.children[selected]?.focus()}});
board.addEventListener('keydown',e=>{const tile=e.target.closest('.tile');if(!tile)return;const index=Number(tile.dataset.index);const delta={ArrowUp:-size,ArrowDown:size,ArrowLeft:-1,ArrowRight:1}[e.key];if(delta===undefined)return;e.preventDefault();const target=index+delta;if(target>=0&&target<pieces.length&&adjacent(index,target)){swap(index,target);board.children[target]?.focus()}});
document.querySelectorAll('#difficulty button').forEach(button=>button.addEventListener('click',()=>setDifficulty(Number(button.dataset.size))));
$('continueButton').addEventListener('click',()=>{const session=readActiveSession();session?resumeGame(session):openGame(nextLevel())});$('shuffleButton').addEventListener('click',shuffle);$('hintButton').addEventListener('click',showHint);$('closeButton').addEventListener('click',closeGame);$('backButton').addEventListener('click',closeGame);$('galleryButton').addEventListener('click',closeGame);$('nextButton').addEventListener('click',()=>openGame((current+1)%scenes.length));$('soundButton').addEventListener('click',()=>{soundOn=!soundOn;$('soundButton').setAttribute('aria-pressed',String(soundOn));$('soundButton').querySelector('span').textContent=soundOn?'音效開':'音效關'});window.addEventListener('popstate',()=>{if($('gameOverlay').hidden)return;try{history.pushState({shijingGame:true},'',`${baseUrl}#game`);gameHistoryActive=true}catch{}showBackNotice()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('gameOverlay').hidden)closeGame()});
function isInstalled(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true}
function showInstallGuide(){const apple=/iphone|ipad|ipod/i.test(navigator.userAgent)||(/macintosh/i.test(navigator.userAgent)&&navigator.maxTouchPoints>1);const android=/android/i.test(navigator.userAgent);$('installInstructions').textContent=apple?'請先關閉此說明，再於 Safari 點「分享」→「加入主畫面」→「加入」。':android?'請先關閉此說明，再於 Chrome 點右上角「⋮」，選「安裝應用程式」或「加到主畫面」。':'請先關閉此說明，再使用 Chrome 或 Edge 網址列的安裝圖示，或從瀏覽器選單選擇安裝。';$('installDialog').showModal()}
$('installButton').addEventListener('click',async()=>{if(!deferredInstallPrompt){showInstallGuide();return}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null});$('installClose').addEventListener('click',()=>$('installDialog').close());$('installDialog').addEventListener('click',e=>{if(e.target===$('installDialog'))$('installDialog').close()});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;$('installButton').hidden=true});if(isInstalled())$('installButton').hidden=true;
renderGallery();
if('serviceWorker'in navigator){
  navigator.serviceWorker.addEventListener('message',event=>{
    if(event.data?.type==='OFFLINE_STATUS')$('offlineStatus').textContent=event.data.ready?'✓ 離線遊玩已準備好':'首次連線下載風景中，請保持連線。';
  });
  window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js')
    .then(()=>navigator.serviceWorker.ready)
    .then(registration=>registration.active?.postMessage({type:'CHECK_OFFLINE'}))
    .catch(()=>$('offlineStatus').textContent='此瀏覽器無法啟用離線快取。'));
}else $('offlineStatus').textContent='此瀏覽器不支援離線快取。';
